mod print;
mod variables;
mod types;
mod strings;
mod tuples;
mod arrays;
mod vectors;
mod conditionals;
mod functions;
mod pointers;
mod structs;
mod enums;
mod cli;
mod mmatch;
mod loops;
mod seacreature;
mod generics;
mod ownership;
mod oopish;
mod boxx;
mod kilke;

fn main() {
    print::run();
    variables::run();
    types::run();
    strings::run();
    tuples::run();
    arrays::run();
    vectors::run();
    conditionals::run();
    functions::run();
    pointers::run();
    structs::run();
    println!("{:?}", enums::run());
    cli::run();
    mmatch::run();
    loops::run();
    seacreature::run();
    generics::run();
    ownership::run();
    oopish::run();
    boxx::run();
    kilke::run();
}