// mod print;
// mod variables;
// mod types;
// mod strings;
// mod tuples;
// mod arrays;
// mod vectors;
// mod conditionals;
// mod functions;
// mod pointers;
// mod structs;
// mod enums;
// mod cli;
// mod mmatch;
// mod loops;
// mod seacreature;
// mod generics;
// mod ownership;
// mod oopish;
// mod boxx;
// mod kilke;
// mod collectioon;

// mod codewars_mirror;
// mod codewars_hungarian;
// mod codewars_stones;
// mod codewars_removep;
// mod codewars_century;
// mod codewars_casinochips;
// mod codewars_interlaced;
// mod codewars_sortbybit;
// mod codewars_nsmallest;
// mod codewars_urlshortener;
mod codewars_elevator;

fn main() {
    // codewars_mirror::run();
    // codewars_hungarian::run();
    // codewars_stones::run();
    // codewars_removep::run();
    // codewars_century::run();
    // codewars_casinochips::run();
    // codewars_interlaced::run();
    // codewars_sortbybit::run();
    // codewars_nsmallest::run();
	// codewars_urlshortener::run();
	codewars_elevator::run();

    // collectioon::run();
    // print::run();
    // variables::run();
    // types::run();
    // strings::run();
    // tuples::run();
    // arrays::run();
    // vectors::run();
    // conditionals::run();
    // functions::run();
    // pointers::run();
    // structs::run();
    // println!("{:?}", enums::run());
    // cli::run();
    // mmatch::run();
    // loops::run();
    // seacreature::run();
    // generics::run();
    // ownership::run();
    // oopish::run();
    // boxx::run();
    // kilke::run();
}