pub mod arrays;
pub mod boxx;
pub mod cli;
pub mod collectioon;
pub mod conditionals;
pub mod enums;
pub mod functions;
pub mod generics;
pub mod mmatch;
pub mod oopish;
pub mod ownership;
pub mod pointers;
pub mod print;
pub mod seacreature;
pub mod strings;
pub mod structs;
pub mod tuples;
pub mod types;
pub mod variables;
pub mod vectors;

pub fn runall() {
	arrays::run();
	boxx::run();
	cli::run();
	collectioon::run();
	conditionals::run();
	enums::run().ok();
	functions::run();
	generics::run();
	mmatch::run();
	oopish::run();
	ownership::run();
	pointers::run();
	print::run();
	seacreature::run();
	strings::run();
	structs::run();
	tuples::run();
	types::run();
	variables::run();
	vectors::run();
}